### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by Meaddu** [jainmukul/box#1]
I don't actually understand how this is supposed to work. Can we have a conversation? Will really appreciate that :)

**Comment by mukuljainx** [comment]
yeah sure! 😄

It uses JavaFX and some other libraries, other libraries should be in the project.
For JavaFX, download it from here and include in your IDE.

**Comment by Meaddu** [comment]
Thanks man! Sorry for the late reply, It would really help if you can tell
me what are the prerequisites to learn development for a voice based web
browser exactly like yours? I mean what do i need to learn? Thanks in
advance :)

**Comment by mukuljainx** [comment]
Basic OOP concept, Java, JavaFX (or you can use swing) and how to use google API's, that's all.

**Comment by Meaddu** [comment]
Thank you Sir, I am trying to run your browser but apparently getting a lot
of errors. Is this related to the JRE version i am using? Was it developed
on a previous build?


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
